/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'other' : null } |
  { 'entertainment' : null } |
  { 'food' : null } |
  { 'transport' : null } |
  { 'shopping' : null } |
  { 'housing' : null } |
  { 'health' : null };
export interface CategorySummary { 'total' : number, 'category' : Category }
export interface Expense {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'notes' : [] | [string],
  'category' : Category,
  'amount' : number,
}
export interface SpendingSummary {
  'total' : number,
  'other' : number,
  'entertainment' : number,
  'food' : number,
  'transport' : number,
  'shopping' : number,
  'housing' : number,
  'health' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExpense' : ActorMethod<[Expense], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpenseById' : ActorMethod<[bigint], [] | [Expense]>,
  'getExpenses' : ActorMethod<[], [] | [Array<Expense>]>,
  'getExpensesByAmountRange' : ActorMethod<[number, number], Array<Expense>>,
  'getExpensesByCategory' : ActorMethod<[Category], Array<Expense>>,
  'getExpensesByCategorySummary' : ActorMethod<[], Array<CategorySummary>>,
  'getExpensesSortedByAmount' : ActorMethod<[], Array<Expense>>,
  'getExpensesSortedByCategory' : ActorMethod<[], Array<Expense>>,
  'getSpendingSummary' : ActorMethod<[], SpendingSummary>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateExpense' : ActorMethod<[Expense], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];