/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'other' : IDL.Null,
  'entertainment' : IDL.Null,
  'food' : IDL.Null,
  'transport' : IDL.Null,
  'shopping' : IDL.Null,
  'housing' : IDL.Null,
  'health' : IDL.Null,
});
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'category' : Category,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CategorySummary = IDL.Record({
  'total' : IDL.Float64,
  'category' : Category,
});
export const SpendingSummary = IDL.Record({
  'total' : IDL.Float64,
  'other' : IDL.Float64,
  'entertainment' : IDL.Float64,
  'food' : IDL.Float64,
  'transport' : IDL.Float64,
  'shopping' : IDL.Float64,
  'housing' : IDL.Float64,
  'health' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExpense' : IDL.Func([Expense], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpenseById' : IDL.Func([IDL.Nat], [IDL.Opt(Expense)], ['query']),
  'getExpenses' : IDL.Func([], [IDL.Opt(IDL.Vec(Expense))], ['query']),
  'getExpensesByAmountRange' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getExpensesByCategory' : IDL.Func([Category], [IDL.Vec(Expense)], ['query']),
  'getExpensesByCategorySummary' : IDL.Func(
      [],
      [IDL.Vec(CategorySummary)],
      ['query'],
    ),
  'getExpensesSortedByAmount' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getExpensesSortedByCategory' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getSpendingSummary' : IDL.Func([], [SpendingSummary], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateExpense' : IDL.Func([Expense], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'other' : IDL.Null,
    'entertainment' : IDL.Null,
    'food' : IDL.Null,
    'transport' : IDL.Null,
    'shopping' : IDL.Null,
    'housing' : IDL.Null,
    'health' : IDL.Null,
  });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'category' : Category,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CategorySummary = IDL.Record({
    'total' : IDL.Float64,
    'category' : Category,
  });
  const SpendingSummary = IDL.Record({
    'total' : IDL.Float64,
    'other' : IDL.Float64,
    'entertainment' : IDL.Float64,
    'food' : IDL.Float64,
    'transport' : IDL.Float64,
    'shopping' : IDL.Float64,
    'housing' : IDL.Float64,
    'health' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExpense' : IDL.Func([Expense], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpenseById' : IDL.Func([IDL.Nat], [IDL.Opt(Expense)], ['query']),
    'getExpenses' : IDL.Func([], [IDL.Opt(IDL.Vec(Expense))], ['query']),
    'getExpensesByAmountRange' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getExpensesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getExpensesByCategorySummary' : IDL.Func(
        [],
        [IDL.Vec(CategorySummary)],
        ['query'],
      ),
    'getExpensesSortedByAmount' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getExpensesSortedByCategory' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getSpendingSummary' : IDL.Func([], [SpendingSummary], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateExpense' : IDL.Func([Expense], [], []),
  });
};

export const init = ({ IDL }) => { return []; };